### ISSUE TITLE
Add missing binarization algorithms

### ISSUE THREAD

**Issue by wrznr** [OCR-D/ocrd_olena#1]
`olena` has a few [more algorithms](https://github.com/glazzara/olena/tree/master/scribo/scribo/binarization) than those wrapped here. In particular, `wolf` and `kim` have proven to be very useful for historical data.

**Comment by cneud** [comment]
Btw, [Gamera](https://github.com/DDMAL/Gamera/blob/e0bd310eb649645d941092a32b42acab8138675a/gamera/plugins/binarization.py) also has Python implementations for adaptive binarization via ``Gatos`` and ``Niblack`` methods, both of which have shown particularly good results for historic documents.

**Comment by kba** [comment]
https://gamera.informatik.hsnr.de/docs/gamera-docs/binarization.html

**Comment by bertsky** [comment]
Can this be closed after 9cdeadc and 49863321?

**Comment by cneud** [comment]
@bertsky Fine with me to close. With ``Niblack`` there is now also support for an advanced adaptive thresholding method. 

At some point in the future I still hope to see a solid open implementation of ``Gatos`` [adaptive method](http://users.iit.demokritos.gr/~bgat/PatRec2006.pdf) as it has turned out the superior method in the IMPACT project and in the DIBCO competitions for historical documents that I know of.

Eventually though, neural networks might also take over [binarization](https://www.mdpi.com/2313-433X/5/4/48) or OCR engines become so good that binarization is obsolete ;-)

**Comment by bertsky** [comment]
@cneud I see – thanks for sharing those insights! (Do we have a place to share such knowledge permanently yet?)

**Comment by wrznr** [comment]
@cneud I see one big problem with data-driven binarization that is the missing data! Manual binarization is extremely costly.

**Comment by cneud** [comment]
@wrznr I cannot follow, why data-driven binarization? But yes, we manually created binarization GT in IMPACT with Photoshop, pixel-by-pixel, would not ever want to do that again!

**Comment by wrznr** [comment]
Because neural networks work data-driven in the sense of being trained with huge amounts of data.

**Comment by cneud** [comment]
Indeed, point taken!

**Comment by cneud** [comment]
Will ask my QURATOR colleagues to have a look at this though: https://github.com/masyagin1998/robin

**Comment by bertsky** [comment]
> Fine with me to close. With `Niblack` there is now also support for an advanced adaptive thresholding method.

Unfortunately, the `niblack` implementation (or parameterization?) in Olena seems to have a __big__ problem:
![OCR-D-IMG-BIN_0001 cropped-niblack](https://user-images.githubusercontent.com/38561704/62402620-22705180-b578-11e9-81ed-9fa3c2c7cfac.png)
![OCR-D-IMG-BIN_0001-niblack](https://user-images.githubusercontent.com/38561704/62402621-2308e800-b578-11e9-808f-9ed00e0b140c.png)

Does anyone know what's going on?

**Comment by cneud** [comment]
@bertsky Looks like typical ``Niblack`` results to me, the algorithm tends to be very conservative in removing noise while at the same time attempting clear separation of text and background. Not visually pleasing for the human eye but OK for OCR. See also the examples given in the Gatos paper linked [above](https://github.com/OCR-D/ocrd_olena/issues/1#issuecomment-517038767), pp. 323-324). That's also one of the reasons why I am still so keen to see a full implementation of the ``Gatos`` adaptive thresholding which, again judging by the same paper, is unfortunately a fairly large amount of work.

**Comment by bertsky** [comment]
@cneud thanks for your explanation. I am stunned – this means what is good for OCR can still be totally useless for (rule-based, i.e. filters and graphs based) segmentation, possibly even conversely so. I will have to digest that for a while...

**Comment by bertsky** [comment]
Anyway, I am going to close again – except anyone wants to turn this into a discussion thread.

**Comment by bertsky** [comment]
> Looks like typical `Niblack` results to me, the algorithm tends to be very conservative in removing noise while at the same time attempting clear separation of text and background. Not visually pleasing for the human eye but OK for OCR.

@cneud I tried this with Ocropy and Tesseract on the GT bags and the results are devastating (in comparison to the other Olena algorithms and to Ocropy nlbin and even Tesseract's own binarization). Is it possible this binarization only gives good results if the OCR can be trained on it? (If so, what OCRs/models should be expected to work with Niblack? Will they also work well on other methods?)

**Comment by cneud** [comment]
@bertsky Plz don't waste your time with this! We're now looking at https://github.com/ajgallego/document-image-binarization in QURATOR which seems to give much more promising results (from the paper). 

TBH the only time I saw a really good implementation of ``Niblack`` for OCR was in the B.I.T. Alpha OCR which a) seems to no longer exist and b) had a terrible sales/support model (while I believe they were the first to introduce NNs for OCR, even before Tom Breuel did). You can find some historic info on this in [here](https://www.slideshare.net/impactproject/bit-alpha-icoc) and [here](https://staatsbibliothek-berlin.de/fileadmin/user_upload/zentrale_Seiten/historische_drucke/pdf/SBB_OCR_STUDIE_WEBVERSION_Final.pdf). Even the [Internet Archive](https://web.archive.org/web/20041211152655/http://bit.dyndns.biz/) does not have much on them anymore.

**Comment by cneud** [comment]
@bertsky a QURATOR colleague has now trained models with different augmentation and parametrization based on https://github.com/ajgallego/document-image-binarization, and the results look quite good I'd say (scaled down and converted to JPG for GitHub)! 

An OCR-D processor version of that binarization could be made available some time in October I guess.

![00000004](https://user-images.githubusercontent.com/952378/63592437-e433e400-c5b1-11e9-9c2d-889c6e93d748.jpg)
![00000004_bin](https://user-images.githubusercontent.com/952378/63592435-e433e400-c5b1-11e9-88e4-3e441b61fa67.jpg)

![00436740](https://user-images.githubusercontent.com/952378/63592440-e4cc7a80-c5b1-11e9-8964-2cd1b22c87be.jpg)
![00436740_bin](https://user-images.githubusercontent.com/952378/63592438-e4cc7a80-c5b1-11e9-86dc-a9e9f8555422.jpg)

![00436721](https://user-images.githubusercontent.com/952378/63592442-e4cc7a80-c5b1-11e9-899c-6a8ef3b891b0.jpg)
![00436721_bin](https://user-images.githubusercontent.com/952378/63592441-e4cc7a80-c5b1-11e9-978d-23384f17564e.jpg)

**Comment by bertsky** [comment]
Follow up on [above question about niblack results](https://github.com/OCR-D/ocrd_olena/issues/1#issuecomment-517865983): to be fair, the `niblack` algorithm was encapsulated differently in scribo. When I use `--disable-negate-input`, I get the following (which looks better, but the issue that this does not work at all for layout analysis, and that it probably must be trained into OCR remains):

![euler-01](https://user-images.githubusercontent.com/38561704/70722802-d1bff080-1cef-11ea-881c-37b30b8ab00d.png)

**Comment by cneud** [comment]
@bertsky Btw we now have released a first version of [our binarization](https://github.com/qurator-spk/sbb_binarization) based on https://github.com/OCR-D/ocrd_olena/issues/1#issuecomment-524296380 and I hope to add an OCR-D interface for it in the next week.

**Comment by bertsky** [comment]
> Btw we now have released a first version of [our binarization](https://github.com/qurator-spk/sbb_binarization) based on [#1 (comment)](https://github.com/OCR-D/ocrd_olena/issues/1#issuecomment-524296380) and I hope to add an OCR-D interface for it in the next week.

@cneud thanks – good to know! If we want to wrap this for OCR-D, we need a stable API though, and the possibility to load the TF model once, then apply on multiple images. Do you want me to open issues there, or is this still in flux anyway?

**Comment by cneud** [comment]
Yes, this repo will still require some code cleanup/refinement, but feel free to open issues already or otherwise I'll let you know once I have a first version of the interface up.
