### ISSUE TITLE
Invalid PAGE-files

### ISSUE THREAD

**Issue by EEngl52** [OCR-D/ocrd_olena#22]
```ocrd-olena-binarize -I OCR-D-CROP -O OCR-D-BIN -p '{"impl":"wolf"}'```

produces invalid PAGE-files (label element, cf. the attachment) 

[OCR-D-BIN_0001.zip](https://github.com/OCR-D/ocrd_olena/files/3983928/OCR-D-BIN_0001.zip)

**Comment by bertsky** [comment]
Confirmed. I forgot to use the proper namespace prefix when I added the metadata. Sorry about that!

@kba, shall I wait for you to finish #19 or make an independent PR right away?

**Comment by kba** [comment]
If it's a simple fix, feel free to open a PR, #19 needn't block this. Or even add it to #19, I'm still wrangling assets anyway.

**Comment by bertsky** [comment]
It is. Chose the latter option.
