### ISSUE TITLE
Build fails under certain preconditions

### ISSUE THREAD

**Issue by stweil** [OCR-D/ocrd_olena#23]
A recent update caused a failing build which can be reproduced, for example like this:

    $ touch olena-add-bin-negate-toggles.patch && make build-olena
    git clone https://gitlab.lrde.epita.fr/olena/olena.git olena-git
    fatal: destination path 'olena-git' already exists and is not an empty directory.
    make: *** [Makefile:49: olena-git] Error 128

A simple ad-hoc fix is `touch olena-git`.

I see two possible solutions to make the build more robust:

- Use a submodule for olena-git. Then `git clone [...]` can be replaced by `git submodule update --init olena-git`.
- Run `git -C olena-git pull` instead of `git clone [...]` if `olena-git` was already cloned.

The first solution would have the additional advantage of using a known revision of `olena` instead of using `HEAD`.

**Comment by kba** [comment]
+1 for submodules.

**Comment by bertsky** [comment]
There is still the problem that we want additional patches that are not accepted upstream (yet). Maybe we want to redefine our upstream to some fork of our own. In that case I'd also prefer a submodule solution like in ocrd_all.

**Comment by kba** [comment]
> There is still the problem that we want additional patches that are not accepted upstream (yet).

Yeah, if we had our own fork, we could simplify further. I think I will do that now, forking from https://github.com/glazzara/olena and adding the merged PR from LRDE's Gitlab as well as applying the patches directly.

**Comment by stweil** [comment]
Currently only two patches are missing in upstream.

**Comment by stweil** [comment]
https://github.com/glazzara/olena is more than 5 years behind the official code. Wouldn't it be better to fork https://gitlab.lrde.epita.fr/olena/olena.git?

**Comment by bertsky** [comment]
Yes, fork from LRDE directly, then pull from https://gitlab.lrde.epita.fr/bertsky/olena/commit/e0fc4dc9d8679f359fcfb46f6109204f5bb3e699, then apply the remaining patches `olena-disable-doc.patch` and `olena-configure-python3.patch` as commit respectively. Not sure we still need the latter, though.

**Comment by kba** [comment]
I forked from https://github.com/glazzara/olena to make the connection clear on GitHub. Applied the merge requests 1 and 2 from Gitlab and then the patches from ocrd_olena. If you prefer @bertsky I can reuse the commit of your Gitlab fork, I set the commit message and author (https://github.com/OCR-D/olena/commit/ed5eecbf8faab5236b1f24911ba7eb2cabe43c83).

**Comment by kba** [comment]
I think this has been resolved with #24 @stweil
