### ISSUE TITLE
ocrd-olena-binarize produces invalid workspace

### ISSUE THREAD

**Issue by mikegerber** [OCR-D/ocrd_olena#38]
Given the METS [mets.zip](https://github.com/OCR-D/ocrd_olena/files/4293761/mets.zip), I get after binarization (`ocrd-olena-binarize -I PRESENTATION -O OCR-D-IMG-BINPAGE,OCR-D-IMG-BIN -p '{ "impl": "sauvola-ms-split") }'`, 1.1.3/2.4.2) these errors:

~~~
% ocrd workspace validate
[... lots and lots of errors ...]
<error>PAGE-XML OCR-D-IMG-BINPAGE/FILE_0420_OCR-D-IMG-BINPAGE.xml : imageFilename '/srv/digisam_images/sbb/PPN719671574/00000420.tif' not found in METS</error>
[...]
~~~
(The workspace validated before running binarisation.)

However, the files are there:
~~~
% grep /srv/digisam_images/sbb/PPN719671574/00000420.tif mets.xml
        <mets:FLocat xmlns:xlink="http://www.w3.org/1999/xlink" LOCTYPE="URL" xlink:href="file:///srv/digisam_images/sbb/PPN719671574/00000420.tif"/>
~~~

* Should the `xlink:href` be a path?
* Should the image filename in `FILE_0420_OCR-D-IMG-BINPAGE.xml` be a `file://` URL?

**Comment by mikegerber** [comment]
(JPAGEViewer does not open the `FILE_0420_OCR-D-IMG-BINPAGE.xml` with the absolute path in the `imageFilename`, prepended with `file://` or not.)

**Comment by bertsky** [comment]
>     * Should the `xlink:href` be a path?

Only if `LOCTYPE="OTHER" OTHERLOCTYPE="FILE"`, not for `LOCTYPE="URL"` IIRC.

We deprecated creating `file://` URLs ourselves, but must nevertheless be able to cope with that if it comes in, as is the case here.

>     * Should the image filename in `FILE_0420_OCR-D-IMG-BINPAGE.xml` be a `file://` URL?

I have never seen it like this. But it's what the spec would suggest:

> [page.md]
> ### URL for imageFilename / filename
> The imageFilename of the <pg:Page> and filename of the <pg:AlternativeImage> element MUST be a URL. A local filename should be a file:// URL.
> 
> All URL used in imageFilename and filename MUST be referenced in a fileGrp in METS.

However, I must add that this formulation dates from 16 months ago, when we still tried to stay on `file://` references (together with some book-keeping in the back). In other, up-to-date places the spec says something quite different:

> [mets.md]
> ### Always use URL or relative filenames
> 
> Always use URL, except for files located in the directory or any subdirectories of the METS file.

So I guess we should allow both `file://` URLs and local relative paths, but clearly what is not warranted is a local absolute path without `file://` prefix, as is produced right now. Thanks for reporting!

The culprit is not in core (as I suspected at first sight), but right here in the [shell script](https://github.com/OCR-D/ocrd_olena/blob/69ab1cc4bafce049cd479e45713d52d09253d738/ocrd-olena-binarize#L341): it queries the workspace's `local_filename` entry to get to the file for processing, but neglects to also look at the `url` entry to be annotated in the PAGE-XML.

> (JPAGEViewer does not open the `FILE_0420_OCR-D-IMG-BINPAGE.xml` with the absolute path in the `imageFilename`, prepended with `file://` or not.)

Even if you trick it with `--resolve-dir ""`?

**Comment by bertsky** [comment]
@mikegerber could you please try again with #39 on your input? (We have no malign URLs tests for this yet.)

**Comment by kba** [comment]
> > ### URL for imageFilename / filename
> > The imageFilename of the pg:Page and filename of the pg:AlternativeImage element MUST be a URL. A local filename should be a file:// URL.
> > All URL used in imageFilename and filename MUST be referenced in a fileGrp in METS.
> 
> However, I must add that this formulation dates from 16 months ago, when we still tried to stay on `file://` references (together with some book-keeping in the back). In other, up-to-date places the spec says something quite different:

This is indeed outdated, c.f. https://github.com/OCR-D/spec/pull/140 We'll update the specs asap.

**Comment by mikegerber** [comment]
> > (JPAGEViewer does not open the `FILE_0420_OCR-D-IMG-BINPAGE.xml` with the absolute path in the `imageFilename`, prepended with `file://` or not.)
> Even if you trick it with `--resolve-dir ""`?

They now support the absolute filenames (https://github.com/PRImA-Research-Lab/prima-page-viewer/issues/11)!

**Comment by mikegerber** [comment]
I'm not sure what behavior exactly #39 changed? Anyways, it seems that this should be ok:

~~~
<?xml version="1.0" encoding="UTF-8"?>
<PcGts xmlns:xsl="http://www.w3.org/1999/XSL/Transform#" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schema.primaresearch.org/PAGE/gts/pagecontent/2019-07-15" xsi:schemaLocation="http://schema.primaresearch.org/PAGE/gts/pagecontent/2019-07-15 http://schema.primaresearch.org/PAGE/gts/pagecontent/2019-07-15/pagecontent.xsd">
  <Metadata>
    <Creator>OCR-D/core 2.4.2</Creator>
    <Created>2020-03-09T15:07:27</Created>
    <LastChange>2020-03-09T15:07:27</LastChange>
    <MetadataItem type="processingStep" name="preprocessing/optimization/binarization" value="ocrd-olena-binarize">
      <Labels>
        <Label value="101" type="win-size"/>
        <Label value="sauvola" type="impl"/>
        <Label value="0.34" type="k"/>
      </Labels>
    </MetadataItem>
  </Metadata>
  <Page imageFilename="/srv/digisam_images/sbb/PPN726351202/00000001.tif" imageWidth="2291" imageHeight="4116" type="content">
    <AlternativeImage filename="OCR-D-IMG-BIN/FILE_0001_OCR-D-IMG-BINPAGE-BIN_sauvola.png" comments="binarized"/>
  </Page>
</PcGts>
~~~

That is a full absolute path in `imageFilename`, produced by `ocrd-olena-binarize` (master), but this does not validate:

~~~
% ocrd workspace validate
[...]
  <error>PAGE-XML OCR-D-IMG-BINPAGE/FILE_0001_OCR-D-IMG-BINPAGE.xml : imageFilename '/srv/digisam_images/sbb/PPN726351202/00000001.tif' not found in METS</error>
[...]
~~~

~~~
 % grep /srv/digisam_images/sbb/PPN726351202/00000001.tif mets.xml
        <mets:FLocat xmlns:xlink="http://www.w3.org/1999/xlink" LOCTYPE="URL" xlink:href="file:///srv/digisam_images/sbb/PPN726351202/00000001.tif"/>
~~~

Is it a bug in core or something with my data? Or is this use unsupported? (I think it should be supported, as I work with supposedly valid METS from our library.)

**Comment by bertsky** [comment]
> I'm not sure what behavior exactly #39 changed?

Nothing in this case – sorry! I made a [mistake](https://github.com/OCR-D/ocrd_olena/pull/39#discussion_r389733908) and must fix again.

**Comment by bertsky** [comment]
> Anyways, it seems that this should be ok:
> ... `imageFilename="/srv/digisam_images/sbb/PPN726351202/00000001.tif" ` ...
> That is a full absolute path in imageFilename, produced by ocrd-olena-binarize (master)

As stated above, this is _not_ a correct representation:
> but clearly what is not warranted is a local absolute path without file:// prefix, as is produced right now

The validator is fine.

**Comment by mikegerber** [comment]
> > but clearly what is not warranted is a local absolute path without file:// prefix, as is produced right now
> The validator is fine.

It's also complaining when using the `file://` prefix.

**Comment by bertsky** [comment]
> > > The validator is fine.
> 
> It's also complaining when using the `file://` prefix.

oh! @kba?
