### ISSUE TITLE
scribo does not pass k parameter to sauvola ms

### ISSUE THREAD

**Issue by bertsky** [OCR-D/ocrd_olena#40]
See upstream [description](https://gitlab.lrde.epita.fr/olena/olena/issues/6) and [solution](https://gitlab.lrde.epita.fr/olena/olena/-/merge_requests/4).

I don't know how long we will have to wait for this to be merged. Maybe we could merge into OCR-D/olena right away – @kba?

**Comment by kba** [comment]
[Merged in OCR-D/olena](https://github.com/OCR-D/olena/commit/a797d18c9ed12aaf5f2276e0faefc8e6e7e2b313)

**Comment by bertsky** [comment]
> Merged in OCR-D/olena

Thanks!

~~Do you want me to update `repo/olena` to this state in #41?~~ ok just saw #42

**Comment by bertsky** [comment]
Fixed via #42
