### ISSUE TITLE
make install woes

### ISSUE THREAD

**Issue by mikegerber** [OCR-D/ocrd_olena#61]
I have some weird problems with the Makefile - make install fails to install /usr/local/bin/ocrd-olena-binarize:

~~~
% sudo make install PREFIX=/usr/local
test -x /usr/local/bin/scribo-cli && \
/usr/local/bin/scribo-cli sauvola --help >/dev/null 2>&1 || \
	make build-olena
which ocrd >/dev/null 2>&1 || \
	/usr/bin/pip3 install ocrd # needed for ocrd CLI (and bashlib)
~~~

I read the Makefile that `install` depends on `/usr/local/bin/ocrd-olena-binarize` existing but it doesn't:

~~~
% ls -l /usr/local/bin/ocrd-olena-binarize
ls: cannot access '/usr/local/bin/ocrd-olena-binarize': No such file or directory
~~~

More weirdly, without sudo, it tries to install:

~~~
% make install PREFIX=/usr/local
test -x /usr/local/bin/scribo-cli && \
/usr/local/bin/scribo-cli sauvola --help >/dev/null 2>&1 || \
	make build-olena
which ocrd >/dev/null 2>&1 || \
	/usr/bin/pip3 install ocrd # needed for ocrd CLI (and bashlib)
sed 's|^SHAREDIR=.*|SHAREDIR="/usr/local/share/ocrd_olena"|;s|^PYTHON=.*|PYTHON="/usr/bin/python3"|' ocrd-olena-binarize > /usr/local/bin/ocrd-olena-binarize
/bin/sh: /usr/local/bin/ocrd-olena-binarize: Permission denied
make: *** [Makefile:82: /usr/local/bin/ocrd-olena-binarize] Error 1
~~~

**Comment by mikegerber** [comment]
Another thing: that `sudo make install` defaults to installing to `/local` is a bit unexpected:

~~~
 % sudo make install
test -x /local/bin/scribo-cli && \
/local/bin/scribo-cli sauvola --help >/dev/null 2>&1 || \
~~~

**Comment by mikegerber** [comment]
Ah, the Makefile relies on `ocrd` working to read from `ocrd-tool.json`, in that case I had a broken ocrd install for the root user → this was tricky to debug. 

I leave the issue open as it's maybe worth discussing if it's a bug that this line fails silently (if it fails):

~~~
TOOLS = $(shell ocrd ocrd-tool ocrd-tool.json list-tools 2>/dev/null)
~~~

**Comment by kba** [comment]
We could do a more robust test than just `which ocrd` , e.g. `ocrd ocrd-tool --help`. Would that have helped?

**Comment by mikegerber** [comment]
I think so (fixed the ocrd install already) but it's also a bit hard to handle such broken installs, so I'd leave it up to you.

**Comment by mikegerber** [comment]
Main issue seems to be here that `$(shell foo)` does not fail if `foo` fails, then there would at least an error to look at.
