### ISSUE TITLE
remove Travis CI

### ISSUE THREAD

**Issue by mikegerber** [OCR-D/ocrd_olena#65]
See https://travis-ci.org/github/OCR-D/ocrd_olena/builds/713616420.

I think https://github.com/OCR-D/ocrd_olena/blob/master/.travis.yml is missing a `make install`. I have absolutely no idea why this wasn't noticed earlier.

**Comment by mikegerber** [comment]
I noticed there is both Travis and CircleCI running, this is a bit confusing. @kba?

**Comment by kba** [comment]
I haven't used Travis in a long while, CircleCI was faster and more comfortable to work with. We should probably ditch Travis but if it's not too much effort to fix, I'll do that for now.

**Comment by mikegerber** [comment]
I vote for removing Travis and having only one CI.

**Comment by mikegerber** [comment]
However I was already testing #66, build is still running

**Comment by kba** [comment]
> I vote for removing Travis and having only one CI.

I don't feel strongly one way or the other. But maybe @bertsky does. Let's wait for him to return from vacation.

For now, I think #66 fixed Travis, waiting for https://travis-ci.org/github/OCR-D/ocrd_olena/builds/713665797 to finish.

**Comment by bertsky** [comment]
> I think https://github.com/OCR-D/ocrd_olena/blob/master/.travis.yml is missing a `make install`. I have absolutely no idea why this wasn't noticed earlier.

But `test` already depended on `install`. My guess is the deeper reason for this failure was the [broken TOOLS logic](https://github.com/OCR-D/ocrd_olena/pull/59#issuecomment-666993067) detected by you.

> > I vote for removing Travis and having only one CI.
> 
> I don't feel strongly one way or the other. But maybe @bertsky does. Let's wait for him to return from vacation.

No hard feelings here about removing the Travis setup.

**Comment by mikegerber** [comment]
> > I think https://github.com/OCR-D/ocrd_olena/blob/master/.travis.yml is missing a `make install`. I have absolutely no idea why this wasn't noticed earlier.
> But `test` already depended on `install`. My guess is the deeper reason for this failure was the [broken TOOLS logic](https://github.com/OCR-D/ocrd_olena/pull/59#issuecomment-666993067) detected by you.

The Makefile `test` target does not depend on `install` AFAICS, or do you mean something else?

**Comment by bertsky** [comment]
> The Makefile `test` target does not depend on `install` AFAICS, or do you mean something else?

ha! You're right – not anymore: ed2d93f7

@kba could you please explain why you removed that dependency?

**Comment by kba** [comment]
> 
> 
> > The Makefile `test` target does not depend on `install` AFAICS, or do you mean something else?
> 
> ha! You're right – not anymore: [ed2d93f](https://github.com/OCR-D/ocrd_olena/commit/ed2d93f7af89732407acaa036c40a74fe367c5a6)
> 
> @kba could you please explain why you removed that dependency?

Because not every `make test` should run `make install`. It's useful for CI but less so when debugging the tests (which I was doing in that commit). Sry for the confusion but I would prefer to keep it like this and just do `make install` in addition to `make test` in CI.

**Comment by bertsky** [comment]
> Because not every `make test` should run `make install`. It's useful for CI but less so when debugging the tests (which I was doing in that commit).

I see. I'd agree with that in general (although it's surprising to me). But here, `test` (i.e. test.sh) cannot even work without `install`. Perhaps you really just tried to avoid **re-installing** each time you want to run test (so making `install` more selective)?

**Comment by kba** [comment]
> Perhaps you really just tried to avoid re-installing each time you want to run test (so making install more selective)?

Yes.

**Comment by bertsky** [comment]
> > Perhaps you really just tried to avoid re-installing each time you want to run test (so making install more selective)?
> 
> Yes.

Then your recent improvements (`TOOLS` in fe929680, `which` in 18974828) are already sufficient? 

Or should we also improve on `deps` (e.g. by replacing the unconditional functional test with time-stamped explicit executable files under `$PREFIX/libexec/scribo/sauvola` and `$PREFIX/bin/ocrd` etc)?

**Comment by kba** [comment]
> Then your recent improvements (TOOLS in fe92968, which in 1897482) are already sufficient?

I think so, yes. `make test` works nicely now, CircleCI is working and Travis we want to get rid off anyway, right?

**Comment by bertsky** [comment]
> > Then your recent improvements (TOOLS in [fe92968](https://github.com/OCR-D/ocrd_olena/commit/fe929680d77453910a86a913164dadf0d7ccd659), which in [1897482](https://github.com/OCR-D/ocrd_olena/commit/18974828a9ab22a35d37b30707d76401cd7c0f7c)) are already sufficient?
> 
> I think so, yes. `make test` works nicely now, CircleCI is working and Travis we want to get rid off anyway, right?

We do, yes. Could you please check if you are still satisfied with interactively running `make test` repeatedly after re-instating the `install` dependency? (Otherwise I'll make a PR for the above `deps` proposal.)

**Comment by kba** [comment]
Cannot test properly (at work, bash is too old...) but the overhead of running `install` with every `test` is minimal, can be reinstated from my POV.

**Comment by bertsky** [comment]
> Cannot test properly (at work, bash is too old...) but the overhead of running `install` with every `test` is minimal, can be reinstated from my POV.

apart from that, CI still fails because [pip is out-of-date](https://github.com/OCR-D/ocrd_tesserocr/pull/138#issuecomment-673692790).

**Comment by bertsky** [comment]
Sorry, re-opening as a reminder we want to make `install` dependent on `deps` again, and ultimately remove Travis.

**Comment by bertsky** [comment]
> Sorry, re-opening as a reminder we want to make `install` dependent on `deps` again, and ultimately remove Travis.

Both seem to be the case.
