### ISSUE TITLE
ocrd-olena-binarize silently ignores non-existent input file group

### ISSUE THREAD

**Issue by mikegerber** [OCR-D/ocrd_olena#76]
For any workspace, a non-existent input file group is silently ignored, without an error:
~~~
% ocrd-olena-binarize -I DOES-NOT-EXIST -O OCR-D-IMG-BIN 
% 
~~~

Other processors report a much more useful error, e.g.:
~~~
Exception: Invalid input/output file grps:
        Input fileGrp[@USE='OCR-D-IMG-BIN'] not in METS!
~~~

**Comment by mikegerber** [comment]
#75 is somewhat related because it still creates the (empty) output directory.

**Comment by bertsky** [comment]
I believe bashlib's `ocrd__parse_argv` needs to do something along the lines of `ocrd.decorators.ocrd_cli_wrap_processor` here (which calls `WorkspaceValidator.check_file_grp` on the workspace and filegrps).

**Comment by mikegerber** [comment]
A little reasoning why this important: We have a "workflow script" that runs binarization and then layout segmentation. Because the user used the wrong input file group, no binarization was generated and - confusingly - the layout segmentation failed.

**Comment by bertsky** [comment]
With the fix now available in core (and hopefully also ocrd_all) I'd say we can close. Let me know @mikegerber if the problem persists.
