### ISSUE TITLE
aggregate adding files to METS to gain speed

### ISSUE THREAD

**Issue by bertsky** [OCR-D/ocrd_olena#77]
Currently, for each page, after the backend CLI have created the output image and output PAGE, we add both separately to the METS.

Since METS de/serialization may become very slow on large workspaces, it would be better to aggregate all these `ocrd workspace add` commands in the loop into a single `ocrd workspace bulk-add` in the end. (But of course, we would have to be careful with error handling.)

**Comment by bertsky** [comment]
The real problem here is that `bulk-add` needs strict file path names, though. But which page ID and output file ID you get depends on lots of factors (including naming convention on the input side and potential clashes with existing IDs). It is not realistic to reconstruct all information (file ID and page ID) from the file path name alone.

It would be nice if we had a function in core where you can pipe these parameter sets via stdin. Say:

    { echo PHYS_0001 BIN FILE_0001_BIN.IMG-wolf BIN/FILE_0001_BIN.IMG-wolf.png image/png; \
      echo PHYS_0001 BIN FILE_0001_BIN BIN/FILE_0001_BIN.xml application/vnd.prima.page+xml; \
      echo PHYS_0002 BIN FILE_0002_BIN.IMG-wolf BIN/FILE_0002_BIN.IMG-wolf.png image/png; \
      echo PHYS_0002 BIN FILE_0002_BIN BIN/FILE_0002_BIN.xml application/vnd.prima.page+xml; \
    } | ocrd workspace bulk-add -r "(?P<pageid>.*) (?P<filegrp>.*) (?P<fileid>.*) (?P<url>.*) (?P<mimetype>.*)" \
      -G "{{ filegrp }}" -g "{{ pageid }}" -i "{{ fileid }}" -m "{{ mimetype }}" -u "{{ url }}" -

**Comment by bertsky** [comment]
Is now possible to implement.

Can also be used to allow page-parallel processing. See [ocrd-import](https://github.com/bertsky/workflow-configuration/blob/master/ocrd-import) for such an implementation.

**Comment by bertsky** [comment]
Perhaps we could even go one step further – and implement the bulk-add functionality in bashlib directly. Like `ocrd__files` and `ocrd__input_file`, we could provide a bash function `ocrd__output_file` (or `ocrd_add`) that encapsulates
- aggregating all the requests (input for bulk-add)
- running bulk-add in the end

What do you think, @kba?

**Comment by kba** [comment]
That would be even better than the custom solution you provide in #85. I am not sure how much effort that would be to generalize or rather whether that effort is worth the gain, seeing as we have few bashlib processors as opposed to Python processors.
