### ISSUE TITLE
Consider making it possible to not install deps

### ISSUE THREAD

**Issue by mikegerber** [OCR-D/ocrd_olena#79]
This is rather a wishlist item:

Please consider an `install` target that doesn't install `deps` (e.g. `build-olena`). I have Olena pre-built and installed system-/container-wide and I don't want ocrd_olena to build it again for me.

My first idea is changing this in the `Makefile`:
~~~
install: deps
install: $(SHAREDIR)/ocrd-tool.json
install: $(TOOLS:%=$(BINDIR)/%)
...
.PHONY: build-olena clean-olena deps deps-ubuntu help install test clean docker
~~~
to something like this (not tested but hopefully clear what the intention is):
~~~
install: deps install-without-deps
install-without-deps: $(SHAREDIR)/ocrd-tool.json
install-without-deps: $(TOOLS:%=$(BINDIR)/%)
...
.PHONY: build-olena clean-olena deps deps-ubuntu help install install-without-deps test clean docker
~~~

(What I currently do is removing the `install: deps` line with `sed` in my Docker build, which is not as robust as I would wish for.)

**Comment by bertsky** [comment]
Sure, we could differentiate the two groups of targets (which I would rather call `install` vs. `install-tools`).

But it would probably be even better if your (apted) pre-installation would be found by `deps` directly. Since our makefile simply delegates to Olena's makefile, all we have to do is make sure the runtime check for `scribo-cli` works:

https://github.com/OCR-D/ocrd_olena/blob/faf31703aef63516acee43e2e9079ff3e38b850a/Makefile#L66-L69

So perhaps all you would need to do is symlink from your system prefix' `scribo-cli` to `$BINDIR`, i.e. `$PREFIX/bin`, i.e. `$VIRTUAL_ENV/bin`?

**Comment by mikegerber** [comment]
Also, no other processor installs system-dependencies′ (like Tesseract) with `make install`, I would expect this from this processor, too.

For example, ocrd_tesserocr makes installing `deps-ubuntu` a separate step in the documentation. 

¹ Anything that is not installable by pip

**Comment by bertsky** [comment]
> Also, no other processor installs system-dependencies′ (like Tesseract) with `make install`, I would expect this from this processor, too.
> For example, ocrd_tesserocr makes installing `deps-ubuntu` a separate step in the documentation.

The `deps-ubuntu` part is independent here as well. In fact, this module does not (attempt to) install anything system-wide if you call `make install`. But if you define _system dependencies_ as everything beyond `pip` (even if it's just C libraries in the venv), then yes, that's what we need here (and ocrd_tesserocr does a similar thing BTW).

**Comment by mikegerber** [comment]
Please decide as you please - the feedback from me as a user is: please make it possible to *not* compile and install the Olena dependency when installing ocrd_olena. It takes ages to compile this stuff.

**Comment by bertsky** [comment]
> please make it possible to _not_ compile and install the Olena dependency when installing ocrd_olena. It takes ages to compile this stuff.

I know, and like I said, I am sympathetic to your proposal, but please help me by first addressing the above question:

> So perhaps all you would need to do is symlink from your system prefix' `scribo-cli` to `$BINDIR`, i.e. `$PREFIX/bin`, i.e. `$VIRTUAL_ENV/bin`?

(I cannot try this myself as I have no copy of your deb prebuild.)

**Comment by kba** [comment]
> I cannot try this myself as I have no copy of your deb prebuild.)

https://qurator-data.de/~mike.gerber/olena_2.1-0+ocrd-git+1/ (from https://gitter.im/OCR-D/Lobby?at=617a84a6d3ae402e477590ea)

**Comment by mikegerber** [comment]
Yes, that's the deb! I currently install it like this:

https://github.com/qurator-spk/ocrd-galley/blob/master/Dockerfile-ocrd_olena#L14-L19

(No APT repo because interest in the community seemed to be small.)

**Comment by bertsky** [comment]
> So perhaps all you would need to do is symlink from your system prefix' `scribo-cli` to `$BINDIR`, i.e. `$PREFIX/bin`, i.e. `$VIRTUAL_ENV/bin`?

I just checked myself: it _does_ suffice to symlink `/usr/bin/scribo-cli` from your `olena-bin` into `$PREFIX/bin`. All `make install` does after this point is to ensure ocrd/Python stuff is there.

**Comment by mikegerber** [comment]
Sure, that's a workaround.

**Comment by bertsky** [comment]
I implemented both.

**Comment by mikegerber** [comment]
I just had a look at the change: Checking with `command -v` looks a like good solution in addition to splitting the target!
