### ISSUE TITLE
Empty page_id : bad array subscript

### ISSUE THREAD

**Issue by M3ssman** [OCR-D/ocrd_olena#81]
# Description 

## Platform

* `ocrd/all:2021-10-12`
* `ocrd-olena-binarize --version : Version "1.2.3", ocrd/core "2.26.0"`

## Actual Behavior

Running simple Workflow from scratch with only a single starting image and an empty METS, olena-Wrapper crashes likely 
```
+ for csv in "${files[@]}"
+ let n+=1
+ local 'IFS=	'
+ fields=($csv)
+ local fields
+ local 'IFS= 	
'
+ local in_fpath=MAX/16258165.png
+ local in_id=IMG_16258165
+ local in_mimetype=image/png
+ local in_pageId=
+ test -f MAX/16258165.png
/usr/bin/ocrd-olena-binarize: line 439: is_page: bad array subscript
make: *** [OCR-D-BINPAGE] Error 1
Makefile:363: recipe for target 'OCR-D-BINPAGE' failed
make: Leaving directory '/data'
```

## Expected Behavior

No crash if no page_id set.

Please see attached data

[16258165-olena.zip](https://github.com/OCR-D/ocrd_olena/files/7633349/16258165-olena.zip)

**Comment by bertsky** [comment]
Thanks @M3ssman for the report. 

So the file is not associated with an entry in the physical structMap. That's a situation we thought we could rule out for OCR-D (see spec and earlier core pulls regarding pageId allocation). If this is something we have to deal with in real life, then it would help understanding which circumstances are responsible for that state of affairs. Will _no_ files have a page id in such a case, or will there be a mix of mapped and unmapped files? How do you discern derived and primary images files then?

**Comment by bertsky** [comment]
I pushed a workaround on master that fixes this example. You will only get a warning in the end:
```
WARNING ocrd.cli.workspace.add - You did not provide '--page-id/-g', so the file you added is not linked to a specific page
```

Closing for now – please test on further data (we can re-open if the problem persists).

Anyone is still welcome to comment on the general problem.
