### ISSUE TITLE
Cannot read $OCRD_TOOL_JSON: '/usr/local/share/ocrd_olena/ocrd-tool.json'

### ISSUE THREAD

**Issue by MehmedGIT** [OCR-D/ocrd_olena#87]
Running in Singularity in the HPC environment.

```shell
N E X T F L O W  ~  version 21.04.3
Launching `/scratch1/users/mmustaf/operandi/slurm_workspaces/328bdbb0-4c08-4629-98db-4d9c5540424d/workflow-odem.nf` [goofy_marconi] - revision: be1420d5fa
O P E R A N D I - H P C - WORKFLOW ODEM
===========================================
input_file_group    : OCR-D-IMG
mets                : /scratch1/users/mmustaf/operandi/slurm_workspaces/328bdbb0-4c08-4629-98db-4d9c5540424d/f1bf3432-d3b6-4a44-afd8-c403698d1b3b/mets.xml
singularity_wrapper : singularity exec --bind /scratch1/users/mmustaf/operandi/slurm_workspaces/328bdbb0-4c08-4629-98db-4d9c5540424d --bind /scratch1/users/mmustaf/ocrd_models:/usr/local/share --env OCRD_METS_CACHING=true /scratch1/users/mmustaf/ocrd_all_maximum_image.sif
cpus                : 1
ram                 : 32GB

[41/e4273f] Submitted process > ocrd_olena_binarize_0
Error executing process > 'ocrd_olena_binarize_0'

Caused by:
  Process `ocrd_olena_binarize_0` terminated with an error exit status (127)

Command executed:

  singularity exec --bind /scratch1/users/mmustaf/operandi/slurm_workspaces/328bdbb0-4c08-4629-98db-4d9c5540424d --bind /scratch1/users/mmustaf/ocrd_models:/usr/local/share --env OCRD_METS_CACHING=true /scratch1/users/mmustaf/ocrd_all_maximum_image.sif ocrd-olena-binarize -I OCR-D-IMG -O OCR-D-BINPAGE -P dpi 300

Command exit status:
  127

Command output:
  (empty)

Command error:
  ERROR: Cannot read $OCRD_TOOL_JSON: '/usr/local/share/ocrd_olena/ocrd-tool.json'
  ```

The same issue is not observed for other processors which makes me think it is a bashlib related issue.

**Comment by kba** [comment]
```
--bind /scratch1/users/mmustaf/ocrd_models:/usr/local/share
```

It looks to me like you're overriding the whole `/usr/local/share` directory. Did you mean

```
--bind /scratch1/users/mmustaf/ocrd_models:/usr/local/share/ocrd-resources
```

?

**Comment by MehmedGIT** [comment]
Nope. There is no error, I meant exactly what I wanted to achieve. I intentionally bind `/usr/local/share` so it can also find the `/usr/local/share/tessdata` folder. Since that folder is on the same level as `/usr/local/share/ocrd-resources`.

**Comment by kba** [comment]
Yes, but by bind-mounting the whole `/usr/local/share` directory, you're effectively hiding what is in the container already. You can do that of course but need to also provide the contents of the folder in the container.

However, with https://github.com/OCR-D/ocrd_all/pull/380 included, there should be no need for a separate tessdata-mount anymore and you can mount directly to `/models`, i.e.

```
--bind /scratch1/users/mmustaf/ocrd_models:/models
```

**Comment by MehmedGIT** [comment]
> Yes, but by bind-mounting the whole `/usr/local/share` directory, you're effectively hiding what is in the container already.

Yes, that's true. It was not a problem before so I did that.

> However, with https://github.com/OCR-D/ocrd_all/pull/380 included, there should be no need for a separate tessdata-mount anymore and you can mount directly to `/models`, i.e.

I will try that and report back. Thanks!

**Comment by kba** [comment]
I think this has since been fixed, feel free to close if so @MehmedGIT
